#!/usr/bin/env python

""" This is the entry point for PM.
"""
from cement.core import foundation
from pm.core import BaseController

class PmApp(foundation.CementApp):
    class Meta:
        label = 'pm'
        base_controller = BaseController

# Create the main app
app = PmApp()

try:
    # setup the application
    app.setup()

    # run the application
    app.run()
finally:
    # close the app
    app.close()